dictionaries = ["en_gb"]
words = [
    "Beatris",
    "CBOW",
    "Carvalho",
    "Cashtags",
    "Daicu",
    "Diogo",
    "Embeddings",
    "IDF",
    "ILNYC",
    "KNN",
    "Lemmatisation",
    "Lemmatization",
    "Lemmatizer",
    "Lingua",
    "Malakhov",
    "Pereira",
    "UMAP",
    "Yehor",
    "demojization",
    "demojize",
    "distilbert",
    "gensim",
    "gini",
    "hyperparameters",
    "lemmatise",
    "lemmatize",
    "lemmatizing",
    "nltk",
    "overfit",
    "runnng",
    "splitter",
    "stopwords",
    "wordcloud",
]
include_paths = ["**/*.md", "**/*.typ"]
